plugins {
    id 'java'
}

group 'org.github.oleksandrkukotin'
version '1.0-SNAPSHOT'

ext {
    jUnitVersion = "5.11.3"
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.json:json:20240303'
    implementation 'ch.qos.logback:logback-classic:1.5.12'

    testImplementation "org.junit.jupiter:junit-jupiter-api:$jUnitVersion"
    testRuntimeOnly "org.junit.jupiter:junit-jupiter-engine:$jUnitVersion"
}

test {
    useJUnitPlatform()
}